# Generated by Django 4.2.3 on 2024-11-30 10:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)])),
                ('test_name', models.CharField(max_length=25, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('unit', models.CharField(max_length=10, null=True)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
            ],
        ),
    ]
